package cashmachine.gui;

import cashmachine.staticHelper.SingletonConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Vladimir Mandač
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setIcon();
        jButtonSendPsw.setVisible(true);
        jPanelErrorMsg.setVisible(false);
        jLabelErrorMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelForgotPsw = new javax.swing.JPanel();
        jPanelErrorMsg = new javax.swing.JPanel();
        jLabelErrorMsg = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jButtonSendPsw = new javax.swing.JButton();
        jScrollPaneTitle = new javax.swing.JScrollPane();
        jTextAreaTitle = new javax.swing.JTextArea();
        jLabelUorE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));

        jPanelForgotPsw.setMaximumSize(new java.awt.Dimension(500, 400));
        jPanelForgotPsw.setMinimumSize(new java.awt.Dimension(500, 400));
        jPanelForgotPsw.setPreferredSize(new java.awt.Dimension(500, 400));

        jPanelErrorMsg.setBackground(new java.awt.Color(241, 222, 222));
        jPanelErrorMsg.setForeground(new java.awt.Color(184, 72, 70));
        jPanelErrorMsg.setMaximumSize(new java.awt.Dimension(330, 30));
        jPanelErrorMsg.setMinimumSize(new java.awt.Dimension(330, 30));
        jPanelErrorMsg.setPreferredSize(new java.awt.Dimension(330, 30));

        jLabelErrorMsg.setBackground(new java.awt.Color(241, 222, 222));
        jLabelErrorMsg.setForeground(new java.awt.Color(184, 72, 70));

        javax.swing.GroupLayout jPanelErrorMsgLayout = new javax.swing.GroupLayout(jPanelErrorMsg);
        jPanelErrorMsg.setLayout(jPanelErrorMsgLayout);
        jPanelErrorMsgLayout.setHorizontalGroup(
            jPanelErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelErrorMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelErrorMsgLayout.setVerticalGroup(
            jPanelErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelErrorMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldUser.setMaximumSize(new java.awt.Dimension(330, 32));
        jTextFieldUser.setMinimumSize(new java.awt.Dimension(330, 32));
        jTextFieldUser.setPreferredSize(new java.awt.Dimension(330, 32));

        jButtonSendPsw.setForeground(new java.awt.Color(35, 125, 22));
        jButtonSendPsw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/icons/email-send-icon.png"))); // NOI18N
        jButtonSendPsw.setText("Send me a password");
        jButtonSendPsw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSendPsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendPswActionPerformed(evt);
            }
        });

        jScrollPaneTitle.setBorder(null);
        jScrollPaneTitle.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneTitle.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPaneTitle.setMaximumSize(new java.awt.Dimension(330, 125));
        jScrollPaneTitle.setMinimumSize(new java.awt.Dimension(330, 125));
        jScrollPaneTitle.setPreferredSize(new java.awt.Dimension(330, 125));

        jTextAreaTitle.setEditable(false);
        jTextAreaTitle.setBackground(new java.awt.Color(214, 217, 223));
        jTextAreaTitle.setColumns(20);
        jTextAreaTitle.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jTextAreaTitle.setForeground(new java.awt.Color(51, 51, 51));
        jTextAreaTitle.setRows(6);
        jTextAreaTitle.setTabSize(10);
        jTextAreaTitle.setText("Please enter your username or email address \nand click on the button.\nYou will receive a password to your email address\nwith which you registered.");
        jTextAreaTitle.setBorder(null);
        jTextAreaTitle.setMaximumSize(new java.awt.Dimension(330, 80));
        jTextAreaTitle.setMinimumSize(new java.awt.Dimension(330, 80));
        jTextAreaTitle.setSelectionColor(new java.awt.Color(214, 217, 223));
        jScrollPaneTitle.setViewportView(jTextAreaTitle);

        jLabelUorE.setText("Username or Email:");

        javax.swing.GroupLayout jPanelForgotPswLayout = new javax.swing.GroupLayout(jPanelForgotPsw);
        jPanelForgotPsw.setLayout(jPanelForgotPswLayout);
        jPanelForgotPswLayout.setHorizontalGroup(
            jPanelForgotPswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPaneTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanelErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabelUorE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonSendPsw))
        );
        jPanelForgotPswLayout.setVerticalGroup(
            jPanelForgotPswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPaneTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelForgotPswLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelForgotPswLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelUorE))
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jButtonSendPsw))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelForgotPsw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelForgotPsw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendPswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendPswActionPerformed
        // TODO add your handling code here:
        
        String emailFrom, emailPsw;
        
        String username, loginEmail, forgotPsw;
        
        try {
            Connection connection = SingletonConnection.getConnection();
            Statement statement = connection.createStatement();
            
            
            String queryString1 = ("SELECT `email`, `emailpassword` FROM admins");
            ResultSet rs1 = statement.executeQuery(queryString1);

            rs1.first();
            emailFrom = rs1.getString(1);
            emailPsw = rs1.getString(2);
                
            String queryString2 = ("SELECT `username`, `loginemail`, `password` FROM users");
            ResultSet rs2 = statement.executeQuery(queryString2);
            
            while (rs2.next()) {                
                username = rs2.getString(1);
                loginEmail = rs2.getString(2);
                forgotPsw = rs2.getString(3);
            }
                
        } catch (SQLException ex) {
            System.out.println(ex);
            jLabelErrorMsg.setText("There was an error, please try again.");
        }
    }//GEN-LAST:event_jButtonSendPswActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ForgotPassword().setVisible(true);
//            }
//        });
//    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\images\\icons\\Emoticon-Realize-Shock-Forgot-icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSendPsw;
    public static javax.swing.JLabel jLabelErrorMsg;
    private javax.swing.JLabel jLabelUorE;
    public static javax.swing.JPanel jPanelErrorMsg;
    private javax.swing.JPanel jPanelForgotPsw;
    private javax.swing.JScrollPane jScrollPaneTitle;
    private javax.swing.JTextArea jTextAreaTitle;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
