package cashmachine.gui;

import static cashmachine.staticHelper.StaticMethods.clickOnHyperlink;
import static cashmachine.staticHelper.StaticMethods.countryJcBFillData;

/**
 *
 * @author Vladimir Mandač
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterForm
     */
    public RegisterPanel() {
        initComponents();
        countryJcBFillData();
        jButtonLogin.setVisible(true);
        jPanelErrorField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelRecommendation = new javax.swing.JLabel();
        jTextFieldRecommendation = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelRetypePsw = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRetypePswField = new javax.swing.JPasswordField();
        jCheckBoxShowPswR = new javax.swing.JCheckBox();
        jLabelPayPalEmail = new javax.swing.JLabel();
        jTextFieldPayPalEmail = new javax.swing.JTextField();
        jLabelCountry = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxCountry = new javax.swing.JComboBox<>();
        jCheckBoxTermsAndCon = new javax.swing.JCheckBox();
        jLabelTermsAndCon = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jPanelErrorField = new javax.swing.JPanel();
        jLabelErrorField = new javax.swing.JLabel();
        jLabelFooter = new javax.swing.JLabel();
        jLabelDeveloper = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(60, 63, 65));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.GridBagLayout());

        jPanelRegister.setBackground(new java.awt.Color(153, 153, 153));
        jPanelRegister.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        jPanelRegister.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jPanelRegister.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanelRegister.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelRegister.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 76, 94));
        jLabel1.setText("New Account Registration ");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 45, 45));
        jLabel2.setText("Become A Member Today");
        jLabel2.setPreferredSize(new java.awt.Dimension(280, 29));

        jLabel3.setText("Registration is absolutely free and open worldwide. Fill in the form below to become a part of our growing community.");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Please make sure you provide us with your real name and email address.");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/cashmachine-gui.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("Only one account from one IP address is permitted.");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Fields marked with");

        jLabel8.setForeground(java.awt.Color.red);
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("are required.");

        jLabelRecommendation.setText("Recommendation:");

        jLabelFirstName.setText("First Name:");

        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("*");

        jLabelLastName.setText("Last Name:");

        jLabel10.setForeground(java.awt.Color.red);
        jLabel10.setText("*");

        jLabelUsername.setText("Username:");

        jLabel12.setForeground(java.awt.Color.red);
        jLabel12.setText("*");

        jLabelEmail.setText("Email Address:");

        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText("*");

        jLabelPassword.setText("Password:");

        jLabel14.setForeground(java.awt.Color.red);
        jLabel14.setText("*");

        jLabelRetypePsw.setText("Retype Password:");

        jLabel15.setForeground(java.awt.Color.red);
        jLabel15.setText("*");

        jCheckBoxShowPswR.setText("Show Password");

        jLabelPayPalEmail.setText("PayPal Email Address:");

        jLabelCountry.setText("Country:");

        jLabel16.setForeground(java.awt.Color.red);
        jLabel16.setText("*");

        jComboBoxCountry.setMaximumRowCount(5);
        jComboBoxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select your country" }));
        jComboBoxCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBoxTermsAndCon.setText("I am at least 18 years of age and I understand and fully agree to Cash Machine");

        jLabelTermsAndCon.setForeground(new java.awt.Color(0, 73, 147));
        jLabelTermsAndCon.setText("Terms and Conditions.");

        jButtonRegister.setBackground(new java.awt.Color(0, 73, 147));
        jButtonRegister.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonRegister.setForeground(java.awt.Color.white);
        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/icons/Users-Checked-User-icon.png"))); // NOI18N
        jButtonRegister.setText("Confirm");
        jButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonLogin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 73, 147));
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/icons/Go-back-icon.png"))); // NOI18N
        jButtonLogin.setText("Back");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jPanelErrorField.setBackground(new java.awt.Color(241, 222, 222));
        jPanelErrorField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 210, 214)));
        jPanelErrorField.setForeground(new java.awt.Color(184, 72, 70));
        jPanelErrorField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabelErrorField.setBackground(new java.awt.Color(241, 222, 222));
        jLabelErrorField.setForeground(new java.awt.Color(184, 72, 70));

        javax.swing.GroupLayout jPanelErrorFieldLayout = new javax.swing.GroupLayout(jPanelErrorField);
        jPanelErrorField.setLayout(jPanelErrorFieldLayout);
        jPanelErrorFieldLayout.setHorizontalGroup(
            jPanelErrorFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelErrorField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelErrorFieldLayout.setVerticalGroup(
            jPanelErrorFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelErrorField, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jLabelFooter.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabelFooter.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        jLabelFooter.setText("Cash Machine © 2017 - made by ");

        jLabelDeveloper.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabelDeveloper.setForeground(new java.awt.Color(0, 73, 147));
        jLabelDeveloper.setText("Vladimir Mandac");
        jLabelDeveloper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeveloperMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelRegisterLayout.createSequentialGroup()
                        .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelErrorField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9))
                                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegisterLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(jCheckBoxTermsAndCon)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabelTermsAndCon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelRecommendation)
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addComponent(jLabelFirstName)
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel11))
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addComponent(jLabelLastName)
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel10))
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addComponent(jLabelUsername)
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel12)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldRecommendation)
                                        .addComponent(jTextFieldFirstName)
                                        .addComponent(jTextFieldLastName)
                                        .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                                    .addComponent(jLabelCountry)
                                                    .addGap(8, 8, 8))
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15)
                                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                                    .addComponent(jLabelPassword)
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jLabel14))
                                                .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                                    .addComponent(jLabelEmail)
                                                    .addGap(1, 1, 1)
                                                    .addComponent(jLabel13)))
                                            .addGap(6, 6, 6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelPayPalEmail)
                                                .addComponent(jLabelRetypePsw))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelRegisterLayout.createSequentialGroup()
                                            .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRetypePswField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldPayPalEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jCheckBoxShowPswR))
                                        .addComponent(jComboBoxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(356, 356, 356))))
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabelDeveloper)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanelErrorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmail)
                        .addComponent(jLabel13))
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRecommendation)
                        .addComponent(jTextFieldRecommendation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPassword)
                        .addComponent(jLabel14))
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxShowPswR))
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFirstName)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLastName)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRetypePswField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jLabelRetypePsw)))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPayPalEmail)
                    .addComponent(jTextFieldPayPalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTermsAndCon)
                    .addComponent(jLabelTermsAndCon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFooter)
                    .addComponent(jLabelDeveloper)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanelRegister, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        MainFormJFrame.cashMachine.changePanel(new LoginPanel());
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jLabelDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeveloperMouseClicked
        // TODO add your handling code here:
        clickOnHyperlink();
    }//GEN-LAST:event_jLabelDeveloperMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JCheckBox jCheckBoxShowPswR;
    private javax.swing.JCheckBox jCheckBoxTermsAndCon;
    public static javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDeveloper;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelErrorField;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelFooter;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPayPalEmail;
    private javax.swing.JLabel jLabelRecommendation;
    private javax.swing.JLabel jLabelRetypePsw;
    private javax.swing.JLabel jLabelTermsAndCon;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelErrorField;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jRetypePswField;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPayPalEmail;
    private javax.swing.JTextField jTextFieldRecommendation;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
