package cashmachine.gui;

import static cashmachine.staticHelper.StaticMethods.clickOnHyperlink;
import static cashmachine.staticHelper.StaticMethods.startSplashScreen;
import java.awt.Toolkit;

/**
 *
 * @author Vladimir Mandač
 */
public class SplashScreen extends javax.swing.JFrame {

    public static SplashScreen loadingSoftware;

    /**
     * Creates new form MainFormJFrame
     */
    @SuppressWarnings({"LeakingThisInConstructor", "OverridableMethodCallInConstructor"})
    public SplashScreen() {
        loadingSoftware = this;
        initComponents();
        setIcon();
        jPanelErrorMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLoading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLoading = new javax.swing.JLabel();
        jProgressBarLoading = new javax.swing.JProgressBar();
        jLabelImagesGears = new javax.swing.JLabel();
        jLabelChecking = new javax.swing.JLabel();
        jPanelErrorMsg = new javax.swing.JPanel();
        jLabelErrorMsg = new javax.swing.JLabel();
        jLabelDeveloper = new javax.swing.JLabel();
        jLabelFooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelLoading.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLoading.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        jPanelLoading.setForeground(new java.awt.Color(60, 63, 65));
        jPanelLoading.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelLoading.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/cashmachine-gui.png"))); // NOI18N

        jLabelLoading.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelLoading.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoading.setText("0%");

        jLabelImagesGears.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagesGears.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashmachine/images/loading-gears-animation.gif"))); // NOI18N

        jLabelChecking.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N

        jPanelErrorMsg.setBackground(new java.awt.Color(241, 222, 222));
        jPanelErrorMsg.setForeground(new java.awt.Color(184, 72, 70));

        jLabelErrorMsg.setBackground(new java.awt.Color(241, 222, 222));
        jLabelErrorMsg.setForeground(new java.awt.Color(184, 72, 70));

        javax.swing.GroupLayout jPanelErrorMsgLayout = new javax.swing.GroupLayout(jPanelErrorMsg);
        jPanelErrorMsg.setLayout(jPanelErrorMsgLayout);
        jPanelErrorMsgLayout.setHorizontalGroup(
            jPanelErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelErrorMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelErrorMsgLayout.setVerticalGroup(
            jPanelErrorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelErrorMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelDeveloper.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabelDeveloper.setForeground(new java.awt.Color(0, 73, 147));
        jLabelDeveloper.setText("Vladimir Mandac");
        jLabelDeveloper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDeveloper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDeveloperMouseClicked(evt);
            }
        });

        jLabelFooter.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabelFooter.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.color1"));
        jLabelFooter.setText("Cash Machine © 2017 - made by ");

        javax.swing.GroupLayout jPanelLoadingLayout = new javax.swing.GroupLayout(jPanelLoading);
        jPanelLoading.setLayout(jPanelLoadingLayout);
        jPanelLoadingLayout.setHorizontalGroup(
            jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelLoadingLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoadingLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLoadingLayout.createSequentialGroup()
                        .addGroup(jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelErrorMsg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelImagesGears, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(jProgressBarLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(192, 192, 192))))
            .addGroup(jPanelLoadingLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabelFooter)
                .addGap(3, 3, 3)
                .addComponent(jLabelDeveloper)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLoadingLayout.setVerticalGroup(
            jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoadingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLoading)
                    .addComponent(jLabelChecking, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagesGears)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanelLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFooter)
                    .addComponent(jLabelDeveloper)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanelLoading, gridBagConstraints);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDeveloperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDeveloperMouseClicked
        // TODO add your handling code here:
        clickOnHyperlink();
    }//GEN-LAST:event_jLabelDeveloperMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(false);
            }
        });
        startSplashScreen();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("..\\images\\cashmachine.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabelChecking;
    private javax.swing.JLabel jLabelDeveloper;
    public static javax.swing.JLabel jLabelErrorMsg;
    private javax.swing.JLabel jLabelFooter;
    private javax.swing.JLabel jLabelImagesGears;
    public static javax.swing.JLabel jLabelLoading;
    public static javax.swing.JPanel jPanelErrorMsg;
    private javax.swing.JPanel jPanelLoading;
    public static javax.swing.JProgressBar jProgressBarLoading;
    // End of variables declaration//GEN-END:variables

}
